// Generated by CoffeeScript 2.7.0
(function () {
	var _settings, async, cli, commonTasks, localTasks, remoteTasks;

	cli = require('cli');

	async = require('async');

	localTasks = require('./localTasks');

	commonTasks = require('./commonTasks');

	remoteTasks = require('./remoteTasks');

	_settings = require('./settings');

	// CLI commands
	module.exports = {
		init: function () {
			return localTasks.initPM2MeteorSettings(function (err) {
				if (err) {
					return cli.fatal(`${err.message}`);
				} else {
					return cli.info(`${_settings.pm2MeteorConfigName} created!`, true);
				}
			});
		},
		deploy: function (reconfig, cold) {
			var pm2mConf, session;
			cli.spinner('Building your app and deploying to host machine');
			pm2mConf = commonTasks.readPM2MeteorConfig();
			session = remoteTasks.getRemoteSession(pm2mConf);
			return async.series(
				[
					function (cb) {
						return remoteTasks.checkDeps(session, pm2mConf, cb);
					},
					function (cb) {
						return remoteTasks.prepareHost(session, pm2mConf, cb);
					},
					function (cb) {
						return localTasks.generatePM2EnvironmentSettings(pm2mConf, cb);
					},
					function (cb) {
						return localTasks.bundleApplication(pm2mConf, cb);
					},
					function (cb) {
						return remoteTasks.backupLastTar(session, pm2mConf, cb);
					},
					function (cb) {
						return remoteTasks.shipTarBall(session, pm2mConf, cb);
					},
					function (cb) {
						return remoteTasks.extractTarBall(session, pm2mConf, cb);
					},
					function (cb) {
						return remoteTasks.installBundleDeps(session, pm2mConf, cb);
					},
					function (cb) {
						return remoteTasks.reloadApp(session, pm2mConf, reconfig, cold, cb);
					},
				],
				function (err) {
					cli.spinner('', true);
					// Close SSH connection
					remoteTasks.closeSession(session);
					if (err) {
						localTasks.makeClean(function (cleanErr) {
							if (cleanErr) {
								cli.error(cleanErr);
							}
							cli.fatal(`${err.message}`);
							process.exit(1);
						});
					} else {
						localTasks.makeClean(function (cleanErr) {
							if (cleanErr) {
								cli.error(cleanErr);
							}
							cli.ok('Deployed your app on the host machine!');
							process.exit(0);
						});
					}
				},
			);
		},
		reconfig: function () {
			var pm2mConf, session;
			cli.spinner('Deploying new env');
			pm2mConf = commonTasks.readPM2MeteorConfig();
			session = remoteTasks.getRemoteSession(pm2mConf);
			return async.series(
				[
					function (cb) {
						return localTasks.generatePM2EnvironmentSettings(pm2mConf, cb);
					},
					function (cb) {
						return remoteTasks.shipSettings(session, pm2mConf, cb);
					},
					function (cb) {
						return remoteTasks.reloadApp(session, pm2mConf, true, false, cb);
					},
				],
				function (err) {
					cli.spinner('', true);
					remoteTasks.closeSession(session);
					if (err) {
						localTasks.makeClean(function () {
							cli.fatal(`${err.message}`);
							process.exit(1);
						});
					} else {
						localTasks.makeClean(function () {
							cli.ok('Deployed new env settings');
							process.exit(0);
						});
					}
				},
			);
		},
		start: function () {
			var pm2mConf, session;
			cli.spinner('Starting app on host machine');
			pm2mConf = commonTasks.readPM2MeteorConfig();
			session = remoteTasks.getRemoteSession(pm2mConf);
			return async.series(
				[
					function (cb) {
						return remoteTasks.startApp(session, pm2mConf, cb);
					},
				],
				function (err) {
					cli.spinner('', true);
					remoteTasks.closeSession(session);
					if (err) {
						cli.fatal(`${err.message}`);
					} else {
						cli.ok('Started your app!');
					}
					process.exit(err ? 1 : 0);
				},
			);
		},
		stop: function () {
			var pm2mConf, session;
			cli.spinner('Stopping app on host machine');
			pm2mConf = commonTasks.readPM2MeteorConfig();
			session = remoteTasks.getRemoteSession(pm2mConf);
			return async.series(
				[
					function (cb) {
						return remoteTasks.stopApp(session, pm2mConf, cb);
					},
				],
				function (err) {
					cli.spinner('', true);
					remoteTasks.closeSession(session);
					if (err) {
						cli.fatal(`${err.message}`);
					} else {
						cli.ok('Stopped your app!');
					}
					process.exit(err ? 1 : 0);
				},
			);
		},
		status: function () {
			var pm2mConf, session;
			cli.spinner('Checking status');
			pm2mConf = commonTasks.readPM2MeteorConfig();
			session = remoteTasks.getRemoteSession(pm2mConf);
			return async.series(
				[
					function (cb) {
						return remoteTasks.status(session, pm2mConf, cb);
					},
				],
				function (err, result) {
					cli.spinner('', true);
					remoteTasks.closeSession(session);
					if (err) {
						cli.fatal(`${err.message}`);
					} else {
						cli.info(result);
					}
					process.exit(err ? 1 : 0);
				},
			);
		},
		generateBundle: function () {
			var pm2mConf;
			cli.spinner('Generating bundle with pm2-env file');
			pm2mConf = commonTasks.readPM2MeteorConfig();
			return async.series(
				[
					function (cb) {
						return localTasks.generatePM2EnvironmentSettings(pm2mConf, cb);
					},
					function (cb) {
						return localTasks.bundleApplication(pm2mConf, cb);
					},
					function (cb) {
						return localTasks.makeCleanAndLeaveBundle(cb);
					},
				],
				function (err) {
					cli.spinner('', true);
					if (err) {
						cli.fatal(`${err.message}`);
					} else {
						cli.ok(`Generated ${_settings.bundleTarName} with pm2-env file`);
					}
					process.exit(err ? 1 : 0);
				},
			);
		},
		undeploy: function () {
			var pm2mConf, session;
			cli.spinner('Undeploying your App');
			pm2mConf = commonTasks.readPM2MeteorConfig();
			if (!(pm2mConf.allowUndeploy && pm2mConf.allowUndeploy === true)) {
				cli.fatal('Please set ´allowUndeploy´ to true in your pm2-meteor3 settings file!');
				process.exit(1);
				return;
			}
			session = remoteTasks.getRemoteSession(pm2mConf);
			return async.series(
				[
					function (cb) {
						return remoteTasks.killApp(session, pm2mConf, cb);
					},
					function (cb) {
						return remoteTasks.deleteAppFolder(session, pm2mConf, cb);
					},
				],
				function (err) {
					cli.spinner('', true);
					remoteTasks.closeSession(session);
					if (err) {
						cli.fatal(`${err.message}`);
					} else {
						cli.ok('Undeployed your App!');
					}
					process.exit(err ? 1 : 0);
				},
			);
		},
		scale: function (opts) {
			var pm2mConf, session;
			cli.spinner('Scaling your App');
			pm2mConf = commonTasks.readPM2MeteorConfig();
			session = remoteTasks.getRemoteSession(pm2mConf);
			return async.series(
				[
					function (cb) {
						return remoteTasks.scaleApp(session, pm2mConf, opts, cb);
					},
				],
				function (err) {
					cli.spinner('', true);
					remoteTasks.closeSession(session);
					if (err) {
						cli.fatal(`${err.message}`);
					} else {
						cli.ok('Scaled your App');
					}
					process.exit(err ? 1 : 0);
				},
			);
		},
		logs: function () {
			var pm2mConf, session;
			pm2mConf = commonTasks.readPM2MeteorConfig();
			session = remoteTasks.getRemoteSession(pm2mConf);
			return async.series(
				[
					function (cb) {
						return remoteTasks.getAppLogs(session, pm2mConf, cb);
					},
				],
				function (err) {
					remoteTasks.closeSession(session);
					if (err) {
						cli.fatal(`${err.message}`);
					}
					process.exit(err ? 1 : 0);
				},
			);
		},
		revert: function () {
			var pm2mConf, session;
			cli.spinner('Reverting to backup');
			pm2mConf = commonTasks.readPM2MeteorConfig();
			session = remoteTasks.getRemoteSession(pm2mConf);
			return async.series(
				[
					function (cb) {
						return remoteTasks.revertToBackup(session, pm2mConf, cb);
					},
					function (cb) {
						return remoteTasks.extractTarBall(session, pm2mConf, cb);
					},
					function (cb) {
						return remoteTasks.installBundleDeps(session, pm2mConf, cb);
					},
					function (cb) {
						return remoteTasks.reloadApp(session, pm2mConf, true, cb);
					},
				],
				function (err) {
					cli.spinner('', true);
					remoteTasks.closeSession(session);
					if (err) {
						cli.fatal(`${err.message}`);
					} else {
						cli.ok('Reverted and hard-restarted your app.');
					}
					process.exit(err ? 1 : 0);
				},
			);
		},
	};
}).call(this);
