// Generated by CoffeeScript 2.7.0
(function () {
	var CWD, _settings, cli, fs, path;

	fs = require('fs');

	cli = require('cli');

	_settings = require('./settings');

	CWD = process.cwd();

	path = require('path');

	module.exports = {
		readPM2MeteorConfig: function () {
			var conf, lastError;
			conf = null;

			for (const configName of _settings.pm2MeteorConfigNames) {
				try {
					conf = require(path.resolve(CWD, configName));
					// Set default appType for backward compatibility
					if (!conf.appType) {
						conf.appType = 'meteor';
					}
					return conf;
				} catch (error) {
					lastError = error;
					continue;
				}
			}
			var triedFiles = _settings.pm2MeteorConfigNames.join(', ');
			return cli.fatal(
				`Error while trying to read config (tried: ${triedFiles}): ${lastError ? lastError.message : 'No config file found'}`,
			);
		},
	};
}).call(this);
