// Generated by CoffeeScript 2.7.0
(function() {
  var CWD, _settings, cli, fs, path;

  fs = require('fs');

  cli = require('cli');

  _settings = require('./settings');

  CWD = process.cwd();

  path = require('path');

  module.exports = {
    readPM2MeteorConfig: function() {
      var conf, err;
      conf = null;
      
      // Try to read pm2-meteor3 config first
      try {
        conf = require(path.resolve(CWD, _settings.tryReadPm2MeteorConfigName));
        return conf;
      } catch (error) {
        // If pm2-meteor3 config not found, try legacy pm2-meteor config
        try {
          conf = require(path.resolve(CWD, _settings.tryReadPm2MeteorConfigNameLegacy));
          return conf;
        } catch (legacyError) {
          err = legacyError;
          return cli.fatal(`Error while trying to read pm2-meteor config (tried both pm2-meteor3.js and pm2-meteor.js): ${err.message}`);
        }
      }
    }
  };

}).call(this);
