// Generated by CoffeeScript 2.7.0
(function () {
  var CWD, _settings, cli, fs, path;

  fs = require("fs");

  cli = require("cli");

  _settings = require("./settings");

  CWD = process.cwd();

  path = require("path");

  module.exports = {
    readPM2MeteorConfig: function () {
      var conf, err;
      conf = null;

      for (const configName of _settings.pm2MeteorConfigNames) {
        try {
          conf = require(path.resolve(CWD, configName));
          return conf;
        } catch (error) {
          continue;
        }
      }
      return cli.fatal(
        `Error while trying to read pm2-meteor config (tried both pm2-meteor3.json and pm2-meteor.json): ${err.message}`
      );
    },
  };
}).call(this);
