// Generated by CoffeeScript 2.2.4
(function () {
	var CWD,
		_settings,
		abs,
		exec,
		fs,
		getAppSrc,
		inquirer,
		isGitProject,
		path,
		reapplyMeteorSettings,
		url,
		objectWithoutKeys = function (o, ks) {
			var res = {};
			for (var k in o) [].indexOf.call(ks, k) < 0 && {}.hasOwnProperty.call(o, k) && (res[k] = o[k]);
			return res;
		},
		_extends =
			Object.assign ||
			function (target) {
				for (var i = 1; i < arguments.length; i++) {
					var source = arguments[i];
					for (var key in source) {
						if (Object.prototype.hasOwnProperty.call(source, key)) {
							target[key] = source[key];
						}
					}
				}
				return target;
			};

	fs = require('fs');

	({ exec } = require('child_process'));

	path = require('path');

	url = require('url');

	abs = require('abs');

	inquirer = require('inquirer');

	_settings = require('./settings');

	// Cross-platform helper functions
	function copyFileSync(src, dest) {
		if (fs.existsSync(src)) {
			fs.copyFileSync(src, dest);
			return true;
		}
		return false;
	}

	function copyDirSync(src, dest) {
		if (!fs.existsSync(src)) return false;
		if (!fs.existsSync(dest)) {
			fs.mkdirSync(dest, { recursive: true });
		}
		const entries = fs.readdirSync(src, { withFileTypes: true });
		for (const entry of entries) {
			const srcPath = path.join(src, entry.name);
			const destPath = path.join(dest, entry.name);
			if (entry.isDirectory()) {
				copyDirSync(srcPath, destPath);
			} else {
				fs.copyFileSync(srcPath, destPath);
			}
		}
		return true;
	}

	function mkdirpSync(dir) {
		if (!fs.existsSync(dir)) {
			fs.mkdirSync(dir, { recursive: true });
		}
	}

	// Convert Windows paths to Unix paths (for remote server paths)
	function toUnixPath(p) {
		return p.replace(/\\/g, '/');
	}

	// Join paths and convert to Unix style (for remote server)
	function unixPathJoin(...parts) {
		return parts.join('/').replace(/\/+/g, '/');
	}

	CWD = process.cwd();

	isGitProject = function (pm2mConf) {
		if (!pm2mConf.appLocation.local || pm2mConf.appLocation.local.trim() === '') {
			return true;
		} else {
			return false;
		}
	};

	reapplyMeteorSettings = function (pm2mConf) {
		var err, meteorSettingsLocation, meteorSettingsObj, pm2EnvLocation, pm2EnvObj, prettyJson;
		if (isGitProject(pm2mConf) && pm2mConf.meteorSettingsInRepo) {
			if (pm2mConf.meteorSettingsLocation && pm2mConf.meteorSettingsLocation !== '') {
				meteorSettingsObj = {};
				meteorSettingsLocation = path.join(CWD, _settings.gitDirName, pm2mConf.meteorSettingsLocation);
				pm2EnvLocation = path.join(CWD, _settings.pm2EnvConfigName);
				try {
					meteorSettingsObj = require(meteorSettingsLocation);
					pm2EnvObj = require(pm2EnvLocation);
					pm2EnvObj.apps[0].env['METEOR_SETTINGS'] = meteorSettingsObj;
					prettyJson = JSON.stringify(pm2EnvObj, null, 2);
					fs.writeFileSync(_settings.pm2EnvConfigName, prettyJson);
				} catch (error) {
					err = error;
					console.log(err.message);
					return false;
				}
			}
		}
		return true;
	};

	// Local tasks
	getAppSrc = module.exports = {
		initPM2MeteorSettings: function (done) {
			var json, p, prompt, questions;
			json = JSON.parse(JSON.stringify(_settings.pm2MeteorConfigTemplate));
			questions = _settings.inquirerQuestions;
			prompt = inquirer.createPromptModule();
			p = prompt(questions);
			return p.then(function (answers) {
				var MONGO_URL,
					PORT,
					ROOT_URL,
					appLocation,
					appName,
					appType,
					entryPoint,
					nextBuildCommand,
					err,
					host,
					instances,
					meteorBuildFlags,
					meteorSettingsLocation,
					password,
					pem,
					prettyJson,
					username;
				({ appName, appType, appLocation } = answers);
				({ entryPoint, nextBuildCommand, viteBuildCommand } = answers);
				({ meteorSettingsLocation, meteorBuildFlags } = answers);
				({ rootURL: ROOT_URL, port: PORT, mongoURL: MONGO_URL } = answers);
				({
					serverHost: host,
					serverUsername: username,
					serverPassword: password,
					serverPem: pem,
					serverInstances: instances,
				} = answers);

				// Base config
				json.appName = appName;
				json.appType = appType || 'meteor';
				json.appLocation = appLocation;

				// Type-specific config
				if (appType === 'express') {
					json.entryPoint = entryPoint || 'src/index.js';
					// Remove Meteor-specific fields
					delete json.meteorSettingsLocation;
					delete json.meteorSettingsInRepo;
					delete json.meteorBuildFlags;
					delete json.nextBuildCommand;
					// Simplify env
					json.env = { NODE_ENV: 'production', PORT: PORT || 3000 };
				} else if (appType === 'nextjs') {
					json.nextBuildCommand = nextBuildCommand || 'npm run build';
					// Remove unnecessary fields
					delete json.meteorSettingsLocation;
					delete json.meteorSettingsInRepo;
					delete json.meteorBuildFlags;
					delete json.entryPoint;
					delete json.viteBuildCommand;
					// Simplify env
					json.env = { NODE_ENV: 'production', PORT: PORT || 3000 };
				} else if (appType === 'vite') {
					json.viteBuildCommand = viteBuildCommand || 'npm run build';
					// Remove unnecessary fields
					delete json.meteorSettingsLocation;
					delete json.meteorSettingsInRepo;
					delete json.meteorBuildFlags;
					delete json.entryPoint;
					delete json.nextBuildCommand;
					// Simplify env
					json.env = { NODE_ENV: 'production', PORT: PORT || 3000 };
				} else {
					// Meteor
					json.meteorSettingsLocation = meteorSettingsLocation;
					json.meteorBuildFlags = meteorBuildFlags;
					delete json.entryPoint;
					delete json.nextBuildCommand;
					delete json.viteBuildCommand;
					json.env = Object.assign(json.env, { ROOT_URL, PORT, MONGO_URL });
				}

				json.server = Object.assign(json.server, {
					host,
					username,
					password,
					pem,
					instances,
				});
				prettyJson = JSON.stringify(json, null, 2);
				try {
					fs.writeFileSync(_settings.pm2MeteorConfigName, prettyJson);
				} catch (error) {
					err = error;
					done(err);
				}
				return done();
			});
		},
		generatePM2EnvironmentSettings: function (pm2mConf, done) {
			var FORK_PORTS, appJson, envJson, err, meteorSettingsLocation, meteorSettingsObj, otherEnvParams, prettyJson, ref, ref1;
			var appType = pm2mConf.appType || 'meteor';
			envJson = JSON.parse(JSON.stringify(_settings.pm2EnvConfigTemplate));
			appJson = {};
			// Fill appJson
			appJson.name = pm2mConf.appName;
			({ FORK_PORTS } = ref = pm2mConf.env);
			otherEnvParams = objectWithoutKeys(ref, ['FORK_PORTS']);
			appJson.env = _extends({}, otherEnvParams);

			// Set script and args based on app type
			// Use Unix paths for remote server (even when building on Windows)
			var appBaseDir = unixPathJoin(pm2mConf.server.deploymentDir, pm2mConf.appName, 'bundle');
			if (appType === 'nextjs') {
				appJson.script = unixPathJoin(appBaseDir, 'node_modules/next/dist/bin/next');
				appJson.args = 'start -p ' + (pm2mConf.env.PORT || 3000);
				appJson.cwd = appBaseDir;
			} else if (appType === 'vite') {
				appJson.script = unixPathJoin(appBaseDir, 'node_modules/serve/build/main.js');
				var vitePort = (pm2mConf.env && pm2mConf.env.PORT !== undefined && pm2mConf.env.PORT !== null)
					? pm2mConf.env.PORT
					: (pm2mConf.port !== undefined ? pm2mConf.port : 3000);
				appJson.args = 'dist -s -l ' + vitePort;
				appJson.cwd = appBaseDir;
			} else if (appType === 'express') {
				var entryPoint = pm2mConf.entryPoint || 'src/index.js';
				appJson.script = unixPathJoin(appBaseDir, entryPoint);
				appJson.cwd = appBaseDir;
			} else {
				// Meteor (default)
				appJson.script = unixPathJoin(appBaseDir, 'main.js');
			}

			appJson.exec_mode = pm2mConf.server.exec_mode;
			appJson.instances = pm2mConf.server.instances;
			if (pm2mConf.server.interpreter && pm2mConf.server.interpreter !== '') {
				appJson.interpreter = pm2mConf.server.interpreter;
			}
			if (pm2mConf.server.log_date_format && pm2mConf.server.log_date_format !== '') {
				appJson.log_date_format = pm2mConf.server.log_date_format;
			}

			// get Meteor settings (only for Meteor apps)
			meteorSettingsObj = {};
			if (appType === 'meteor' && pm2mConf.meteorSettingsLocation && !pm2mConf.meteorSettingsInRepo) {
				try {
					meteorSettingsLocation = abs(pm2mConf.meteorSettingsLocation);
					meteorSettingsObj = JSON.parse(fs.readFileSync(meteorSettingsLocation, 'utf8'));
				} catch (error) {
					err = error;
					done(err);
				}
				appJson.env['METEOR_SETTINGS'] = meteorSettingsObj;
			}
			envJson.apps.push(appJson);
			if (pm2mConf.server.exec_mode && pm2mConf.server.exec_mode === 'fork_mode' && pm2mConf.server.instances > 1) {
				if (FORK_PORTS && FORK_PORTS.length >= pm2mConf.server.instances - 1) {
					(function () {
						var results = [];
						for (var i = 1, ref1 = pm2mConf.server.instances - 1; 1 <= ref1 ? i <= ref1 : i >= ref1; 1 <= ref1 ? i++ : i--) {
							results.push(i);
						}
						return results;
					})
						.apply(this)
						.forEach(function (ind) {
							var anotherAppJson;
							anotherAppJson = JSON.parse(JSON.stringify(appJson));
							anotherAppJson.name = `${anotherAppJson.name}-${ind + 1}`;
							anotherAppJson.env.PORT = FORK_PORTS[ind - 1];
							anotherAppJson.instances = 1;
							return envJson.apps.push(anotherAppJson);
						});
					envJson.apps[0].name = `${envJson.apps[0].name}-1`;
					envJson.apps[0].instances = 1;
				} else {
					done(new Error('You should define env.FORK_PORTS with min. as much ports as server.instances!'));
				}
			}
			prettyJson = JSON.stringify(envJson, null, 2);
			try {
				fs.writeFileSync(_settings.pm2EnvConfigName, prettyJson);
			} catch (error) {
				err = error;
				done({
					message: `${err.message}`,
				});
			}
			return done();
		},
		bundleApplication: function (pm2mConf, done) {
			var appType = pm2mConf.appType || 'meteor';

			if (appType === 'nextjs') {
				return this.bundleNextjsApplication(pm2mConf, done);
			} else if (appType === 'vite') {
				return this.bundleViteApplication(pm2mConf, done);
			} else if (appType === 'express') {
				return this.bundleExpressApplication(pm2mConf, done);
			} else {
				// Meteor (default for backward compatibility)
				if (isGitProject(pm2mConf)) {
					return this.bundleGitApplication(pm2mConf, done);
				} else {
					return this.bundleLocalApplication(pm2mConf, done);
				}
			}
		},
		bundleLocalApplication: function (pm2mConf, done) {
			var buildScript;
			buildScript = '';
			if (pm2mConf.prebuildScript && pm2mConf.prebuildScript.trim() !== '') {
				buildScript += `cd ${abs(pm2mConf.appLocation.local)} && ${pm2mConf.prebuildScript} && `;
			}
			buildScript += `cd ${abs(pm2mConf.appLocation.local)} && meteor build ${pm2mConf.meteorBuildFlags} --directory ${CWD}`;
			return exec(buildScript, function (err, stdout, stderr) {
				if (err) {
					return done(err);
				} else {
					buildScript = `cd ${CWD} && tar -zcvf ${_settings.bundleTarName} ${_settings.bundleName} ${_settings.pm2EnvConfigName}`;
					return exec(
						buildScript,
						{
							maxBuffer: 1024 * 200000,
						},
						function (err, stdout, stderr) {
							if (err) {
								return done(err);
							} else {
								return done();
							}
						},
					);
				}
			});
		},
		bundleNextjsApplication: function (pm2mConf, done) {
			var appDir, buildScript, buildCmd;
			appDir = abs(pm2mConf.appLocation.local || './');
			buildCmd = pm2mConf.nextBuildCommand || 'npm run build';

			// Check if node_modules exists - skip npm install if it does
			var nodeModulesPath = path.join(appDir, 'node_modules');
			if (fs.existsSync(nodeModulesPath)) {
				console.log('node_modules found, skipping npm install...');
				console.log('Building Next.js app...');
				buildScript = `cd "${appDir}" && ${buildCmd}`;
			} else {
				console.log('Installing dependencies and building Next.js app...');
				buildScript = `cd "${appDir}" && npm install && ${buildCmd}`;
			}

			return exec(buildScript, { maxBuffer: 1024 * 200000, shell: true }, function (err, stdout, stderr) {
				if (err) {
					console.error('Build error:', stderr);
					return done(err);
				}
				console.log('Build completed, creating bundle...');

				// Step 2: Create bundle directory and copy files using Node.js fs
				// Note: node_modules is NOT copied - will be installed on server
				try {
					var bundleDir = path.join(CWD, _settings.bundleName);

					// Create bundle directory
					mkdirpSync(bundleDir);

					// Copy build output
					console.log('Copying .next...');
					copyDirSync(path.join(appDir, '.next'), path.join(bundleDir, '.next'));

					// Copy package files for npm install on server
					console.log('Copying package.json...');
					copyFileSync(path.join(appDir, 'package.json'), path.join(bundleDir, 'package.json'));
					copyFileSync(path.join(appDir, 'package-lock.json'), path.join(bundleDir, 'package-lock.json'));

					// Copy optional files/folders if they exist
					copyDirSync(path.join(appDir, 'public'), path.join(bundleDir, 'public'));
					copyFileSync(path.join(appDir, 'next.config.js'), path.join(bundleDir, 'next.config.js'));
					copyFileSync(path.join(appDir, 'next.config.mjs'), path.join(bundleDir, 'next.config.mjs'));
					copyFileSync(path.join(appDir, 'next.config.ts'), path.join(bundleDir, 'next.config.ts'));

					console.log('Files copied, creating tar...');
				} catch (copyErr) {
					console.error('Copy error:', copyErr.message);
					return done(copyErr);
				}

				// Step 3: Create tar
				var tarScript = process.platform === 'win32'
					? `cd /d "${CWD}" && tar -zcvf ${_settings.bundleTarName} ${_settings.bundleName} ${_settings.pm2EnvConfigName}`
					: `cd "${CWD}" && tar -zcvf ${_settings.bundleTarName} ${_settings.bundleName} ${_settings.pm2EnvConfigName}`;

				return exec(tarScript, { maxBuffer: 1024 * 200000, shell: true }, function (err, stdout, stderr) {
					if (err) {
						console.error('Tar error:', stderr);
						return done(err);
					}
					console.log('Next.js bundle created successfully!');
					return done();
				});
			});
		},
		bundleViteApplication: function (pm2mConf, done) {
			var appDir, buildScript, buildCmd;
			appDir = abs(pm2mConf.appLocation.local || './');
			buildCmd = pm2mConf.viteBuildCommand || 'npm run build';

			// Check if node_modules exists - skip npm install if it does
			var nodeModulesPath = path.join(appDir, 'node_modules');
			if (fs.existsSync(nodeModulesPath)) {
				console.log('node_modules found, skipping npm install...');
				console.log('Building Vite app...');
				buildScript = `cd "${appDir}" && ${buildCmd}`;
			} else {
				console.log('Installing dependencies and building Vite app...');
				buildScript = `cd "${appDir}" && npm install && ${buildCmd}`;
			}

			return exec(buildScript, { maxBuffer: 1024 * 200000, shell: true }, function (err, stdout, stderr) {
				if (err) {
					console.error('Build error:', stderr);
					return done(err);
				}
				console.log('Build completed, creating bundle...');

				// Create bundle: dist/ + minimal package.json (serve only)
				try {
					var bundleDir = path.join(CWD, _settings.bundleName);
					var distPath = path.join(appDir, 'dist');

					if (!fs.existsSync(distPath)) {
						return done(new Error('dist/ folder not found. Run "npm run build" first.'));
					}

					mkdirpSync(bundleDir);

					// Copy dist output
					console.log('Copying dist...');
					copyDirSync(distPath, path.join(bundleDir, 'dist'));

					// Create minimal package.json for serve (static file server)
					var servePackageJson = {
						name: 'vite-app-server',
						version: '1.0.0',
						dependencies: { serve: '^14.2.4' },
					};
					fs.writeFileSync(path.join(bundleDir, 'package.json'), JSON.stringify(servePackageJson, null, 2));

					console.log('Files copied, creating tar...');
				} catch (copyErr) {
					console.error('Copy error:', copyErr.message);
					return done(copyErr);
				}

				// Create tar
				var tarScript = process.platform === 'win32'
					? `cd /d "${CWD}" && tar -zcvf ${_settings.bundleTarName} ${_settings.bundleName} ${_settings.pm2EnvConfigName}`
					: `cd "${CWD}" && tar -zcvf ${_settings.bundleTarName} ${_settings.bundleName} ${_settings.pm2EnvConfigName}`;

				return exec(tarScript, { maxBuffer: 1024 * 200000, shell: true }, function (err, stdout, stderr) {
					if (err) {
						console.error('Tar error:', stderr);
						return done(err);
					}
					console.log('Vite bundle created successfully!');
					return done();
				});
			});
		},
		bundleExpressApplication: function (pm2mConf, done) {
			var appDir;
			appDir = abs(pm2mConf.appLocation.local || './');

			console.log('\nCreating Express bundle...');

			// Create bundle directory and copy files using Node.js fs
			// Note: node_modules is NOT copied - will be installed on server
			try {
				var bundleDir = path.join(CWD, _settings.bundleName);
				var entryPoint = pm2mConf.entryPoint || 'src/index.js';
				var srcDir = path.dirname(entryPoint);

				// Create bundle directory
				mkdirpSync(bundleDir);

				// Copy package files for npm install on server
				console.log('\nCopying package.json...');
				copyFileSync(path.join(appDir, 'package.json'), path.join(bundleDir, 'package.json'));
				copyFileSync(path.join(appDir, 'package-lock.json'), path.join(bundleDir, 'package-lock.json'));

				// Copy source directory
				console.log(`\nCopying ${srcDir}...`);
				copyDirSync(path.join(appDir, srcDir), path.join(bundleDir, srcDir));

				// Copy optional files/folders if they exist
				copyDirSync(path.join(appDir, 'config'), path.join(bundleDir, 'config'));
				copyDirSync(path.join(appDir, 'dist'), path.join(bundleDir, 'dist'));
				copyDirSync(path.join(appDir, 'build'), path.join(bundleDir, 'build'));

				console.log('\nFiles copied, creating tar...');
			} catch (copyErr) {
				console.error('Copy error:', copyErr.message);
				return done(copyErr);
			}

			// Create tar
			var tarScript = process.platform === 'win32'
				? `cd /d "${CWD}" && tar -zcvf ${_settings.bundleTarName} ${_settings.bundleName} ${_settings.pm2EnvConfigName}`
				: `cd "${CWD}" && tar -zcvf ${_settings.bundleTarName} ${_settings.bundleName} ${_settings.pm2EnvConfigName}`;

			return exec(tarScript, { maxBuffer: 1024 * 200000, shell: true }, function (err, stdout, stderr) {
				if (err) {
					console.error('Tar error:', stderr);
					return done(err);
				}
				console.log('\nExpress bundle created successfully!');
				return done();
			});
		},
		bundleGitApplication: function (pm2mConf, done) {
			return exec(
				`cd ${CWD} && git clone ${pm2mConf.appLocation.git} --branch ${pm2mConf.appLocation.branch} ${_settings.gitDirName}`,
				function (err, stdout, stderr) {
					var buildScript;
					if (err) {
						return done(err);
					} else {
						if (reapplyMeteorSettings(pm2mConf) === false) {
							return done({
								message: 'Something went wrong wihile building METEOR_SETTINGS',
							});
						} else {
							buildScript = `cd ${path.join(CWD, _settings.gitDirName)} `;
							if (pm2mConf.prebuildScript && pm2mConf.prebuildScript.trim() !== '') {
								buildScript += `&& ${pm2mConf.prebuildScript} `;
							}
							buildScript += `&& meteor build ${pm2mConf.meteorBuildFlags} --directory ${CWD}`;
							return exec(buildScript, function (err, sdout, stderr) {
								if (err) {
									return done(err);
								} else {
									return exec(
										`cd ${CWD} && tar -zcvf ${_settings.bundleTarName} ${_settings.bundleName} ${_settings.pm2EnvConfigName}`,
										{
											maxBuffer: 1024 * 200000,
										},
										function (err, stdout, stderr) {
											if (err) {
												return done(err);
											} else {
												return done();
											}
										},
									);
								}
							});
						}
					}
				},
			);
		},
		makeClean: function (done) {
			// Cross-platform cleanup using Node.js fs
			try {
				var bundleDir = path.join(CWD, _settings.bundleName);
				var pm2EnvFile = path.join(CWD, _settings.pm2EnvConfigName);
				var tarFile = path.join(CWD, _settings.bundleTarName);
				var gitDir = path.join(CWD, _settings.gitDirName);

				// Remove bundle directory
				if (fs.existsSync(bundleDir)) {
					fs.rmSync(bundleDir, { recursive: true, force: true });
				}
				// Remove pm2-env.json
				if (fs.existsSync(pm2EnvFile)) {
					fs.unlinkSync(pm2EnvFile);
				}
				// Remove bundle.tar.gz
				if (fs.existsSync(tarFile)) {
					fs.unlinkSync(tarFile);
				}
				// Remove git-src directory
				if (fs.existsSync(gitDir)) {
					fs.rmSync(gitDir, { recursive: true, force: true });
				}
				return done();
			} catch (err) {
				return done(err);
			}
		},
		makeCleanAndLeaveBundle: function (done) {
			// Cross-platform cleanup using Node.js fs
			try {
				var bundleDir = path.join(CWD, _settings.bundleName);
				var pm2EnvFile = path.join(CWD, _settings.pm2EnvConfigName);
				var gitDir = path.join(CWD, _settings.gitDirName);

				// Remove bundle directory
				if (fs.existsSync(bundleDir)) {
					fs.rmSync(bundleDir, { recursive: true, force: true });
				}
				// Remove pm2-env.json
				if (fs.existsSync(pm2EnvFile)) {
					fs.unlinkSync(pm2EnvFile);
				}
				// Remove git-src directory
				if (fs.existsSync(gitDir)) {
					fs.rmSync(gitDir, { recursive: true, force: true });
				}
				return done();
			} catch (err) {
				return done(err);
			}
		},
	};
}).call(this);
