// Generated by CoffeeScript 2.7.0
(function () {
	var path;

	path = require('path');

	module.exports = {
		pm2MeteorConfigName: 'pm2-meteor3.json',
		pm2MeteorConfigNames: ['pm2-meteor3.json', 'pm2-meteor3.js', 'pm2-meteor.json', 'pm2-meteor.js'],
		pm2MeteorConfigTemplate: {
			appName: '',
			appType: 'meteor', // 'meteor' | 'nextjs' | 'express' | 'vite'
			appLocation: {
				local: '',
				git: '',
				branch: 'master',
			},
			// Express specific
			entryPoint: 'src/index.js',
			// Next.js specific
			nextBuildCommand: 'npm run build',
			// Vite specific
			viteBuildCommand: 'npm run build',
			// Meteor specific (optional for other types)
			meteorSettingsLocation: '',
			meteorSettingsInRepo: false,
			prebuildScript: '',
			meteorBuildFlags: '',
			env: {
				ROOT_URL: '',
				PORT: 3000,
				MONGO_URL: '',
			},
			server: {
				host: '',
				username: '',
				password: '',
				deploymentDir: '/opt/apps',
				loadProfile: '',
				interpreter: '',
				exec_mode: 'cluster_mode',
				instances: 1,
			},
		},
		pm2EnvConfigName: 'pm2-env.json',
		pm2EnvConfigTemplate: {
			apps: [],
		},
		localBuildDir: '/tmp/pm2-meteor3-builds',
		bundleTarName: 'bundle.tar.gz',
		bundleName: 'bundle',
		backupDir: 'backup',
		gitDirName: 'git-src',
		inquirerQuestions: [
			{
				type: 'input',
				name: 'appName',
				message: 'What is the app name?',
				default: function () {
					return path.basename(process.cwd());
				},
			},
			{
				type: 'list',
				name: 'appType',
				message: 'What type of project is this?',
				choices: ['express', 'nextjs', 'vite', 'meteor'],
				default: 'express',
			},
			{
				type: 'input',
				name: 'appLocation',
				message: 'What is the app location? (path or git url)',
				default: './',
				filter: function (val) {
					var rgx;
					rgx = new RegExp('((git|ssh|http(s)?)|(git@[w.]+))(:(//)?)([w.@:/-~]+)(.git)(/)?');
					if (rgx.test(val) === true) {
						return {
							git: val,
							branch: 'master',
						};
					} else {
						return {
							local: val,
						};
					}
				},
			},
			// Express specific
			{
				type: 'input',
				name: 'entryPoint',
				message: 'What is the entry point for your Express app?',
				default: 'src/index.js',
				when: function ({ appType }) {
					return appType === 'express';
				},
			},
			// Next.js specific
			{
				type: 'input',
				name: 'nextBuildCommand',
				message: 'What is the build command for Next.js?',
				default: 'npm run build',
				when: function ({ appType }) {
					return appType === 'nextjs';
				},
			},
			// Vite specific
			{
				type: 'input',
				name: 'viteBuildCommand',
				message: 'What is the build command for Vite?',
				default: 'npm run build',
				when: function ({ appType }) {
					return appType === 'vite';
				},
			},
			// Meteor specific
			{
				type: 'input',
				name: 'meteorSettingsLocation',
				message: 'Where is the settings JSON file for Meteor located?',
				default: function () {
					return path.resolve('./', 'settings.json');
				},
				when: function ({ appType }) {
					return appType === 'meteor';
				},
			},
			{
				type: 'list',
				name: 'meteorBuildFlags',
				message: 'On which server architecture will your app run?',
				choices: ['os.linux.x86_64', 'os.linux.x86_32', 'os.osx.x86_64', 'os.windows.x86_32'],
				default: 'os.linux.x86_64',
				filter: function (val) {
					return `--architecture ${val}`;
				},
				when: function ({ appType }) {
					return appType === 'meteor';
				},
			},
			{
				type: 'input',
				name: 'rootURL',
				message: 'What will be the ROOT URL of your app?',
				default: function () {
					return '';
				},
				when: function ({ appType }) {
					return appType === 'meteor';
				},
			},
			{
				type: 'input',
				name: 'mongoURL',
				message: 'What is the MongoDB connection string for your apps DB?',
				default: function () {
					return '';
				},
				when: function ({ appType }) {
					return appType === 'meteor';
				},
			},
			// Common questions
			{
				type: 'input',
				name: 'port',
				message: 'On which PORT will your app run?',
				default: function () {
					return 3000;
				},
			},
			{
				type: 'input',
				name: 'serverHost',
				message: 'What is the host name of your production machine?',
				default: function () {
					return '';
				},
			},
			{
				type: 'input',
				name: 'serverUsername',
				message: 'Username?',
				default: function () {
					return '';
				},
			},
			{
				type: 'list',
				name: '_authMethod',
				message: 'Do you want to auth by password or by PEM file?',
				choices: ['password', 'pem file'],
			},
			{
				type: 'password',
				name: 'serverPassword',
				message: 'Password?',
				default: function () {
					return '';
				},
				when: function ({ _authMethod }) {
					if (_authMethod === 'password') {
						return true;
					} else {
						return false;
					}
				},
			},
			{
				type: 'input',
				name: 'serverPem',
				message: 'Where is your PEM file located?',
				default: function () {
					return '~/.ssh/someFile.pem';
				},
				when: function ({ _authMethod }) {
					if (_authMethod === 'pem file') {
						return true;
					} else {
						return false;
					}
				},
			},
			{
				type: 'input',
				name: 'serverInstances',
				message: 'How many instances?',
				default: function () {
					return 1;
				},
			},
		],
	};
}).call(this);
